{"name": "Administrador acessa a aplicação cadastro de usuário com perfis", "status": "failed", "statusDetails": {"message": "AssertionError: Mensagem de sucesso não foi exibida.\n", "trace": "  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"features\\steps\\test_tela_de_usuarios_steps.py\", line 104, in validar_mensagem_sucesso\n    context.tela_de_usuarios_page.validar_mensagem_sucesso()\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\neo_liberalizados-automacao\\pages\\tela_de_usuarios_pages.py\", line 201, in validar_mensagem_sucesso\n    raise AssertionError(\"Mensagem de sucesso não foi exibida.\")\n"}, "steps": [{"name": "Given que o usuário está logado como \"Administrador\"", "status": "passed", "steps": [{"name": "Validando que o usuário está logado como Administrador", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x0000025AF0E3AD50>"}], "start": 1744213814018, "stop": 1744213814033}], "start": 1744213814017, "stop": 1744213814033}, {"name": "Then eu devo ter acesso total ao sistema", "status": "passed", "start": 1744213814033, "stop": 1744213814275}, {"name": "When navega até a tela de usuários - Perfil", "status": "passed", "steps": [{"name": "Navegando até a tela de usuários - Perfil", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x0000025AF0E3AD50>"}], "start": 1744213814276, "stop": 1744213816368}], "start": 1744213814275, "stop": 1744213816368}, {"name": "When o usuário clica no botão \"Novo\" para adicionar usuario", "status": "passed", "start": 1744213816368, "stop": 1744213818494}, {"name": "When clica no dropdown de perfil", "status": "passed", "start": 1744213818494, "stop": 1744213820566}, {"name": "When o usuário seleciona o perfil de usuário, escreve o nome e email", "status": "passed", "start": 1744213820567, "stop": 1744213822874}, {"name": "When o usuário clica em \"Salvar\" para salvar o novo usuário", "status": "passed", "start": 1744213822874, "stop": 1744213824966}, {"name": "Then o sistema exibe uma mensagem de sucesso", "status": "failed", "statusDetails": {"message": "AssertionError: Mensagem de sucesso não foi exibida.\n", "trace": "  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"features\\steps\\test_tela_de_usuarios_steps.py\", line 104, in validar_mensagem_sucesso\n    context.tela_de_usuarios_page.validar_mensagem_sucesso()\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\neo_liberalizados-automacao\\pages\\tela_de_usuarios_pages.py\", line 201, in validar_mensagem_sucesso\n    raise AssertionError(\"Mensagem de sucesso não foi exibida.\")\n"}, "steps": [{"name": "Validando mensagem de sucesso exibida pelo sistema", "status": "failed", "statusDetails": {"message": "AssertionError: Mensagem de sucesso não foi exibida.\n", "trace": "  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"features\\steps\\test_tela_de_usuarios_steps.py\", line 104, in validar_mensagem_sucesso\n    context.tela_de_usuarios_page.validar_mensagem_sucesso()\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\neo_liberalizados-automacao\\pages\\tela_de_usuarios_pages.py\", line 201, in validar_mensagem_sucesso\n    raise AssertionError(\"Mensagem de sucesso não foi exibida.\")\n"}, "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x0000025AF0E3AD50>"}], "start": 1744213824966, "stop": 1744213835000}], "start": 1744213824966, "stop": 1744213835008}, {"name": "Then navega até a tela inicial", "status": "skipped", "start": 1744213835008, "stop": 1744213835008}], "start": 1744213814016, "stop": 1744213835008, "uuid": "1e975e6d-ed95-4d98-96a6-454c0fe1964d", "historyId": "4e869f391d9f3f3ef7b5162211ee3b1f", "fullName": "Gerenciamento de Perfis de Acesso: Administrador acessa a aplicação cadastro de usuário com perfis", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Gerenciamento de Perfis de Acesso"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}