{"name": "Acessar a página de login com sucesso", "status": "failed", "statusDetails": {"message": "AssertionError: O login não foi bem-sucedido; URL atual é https://ibfs.iberdrola.com/adfs/ls/wia?client-request-id=019601ab-a6da-7e64-adb3-e354baf79aef&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQQIARAAjVJLaxNhFM3XaWMMaKOiCN1kUYpYZzKPzEwmULBpYzpJmtAmaZJBkHl8XzKTeXVmktgIrl1JVyLdqeAiItS6ka7c2lV3ShEUBZEutNSFBTem_6BwuZwD557FOTcaZgiaJ8ibGE2Q6WmBo2Se5lI4jTQGT0JWw1OppIJDTUMax_MIqZR3ORp7BZ6Ag5faw9dvv1d3_279HoKZdhC4fjqR0HQPBp4-gD6hwR5hQwfa0Gvp8ggGiXcA7APwE4Dh2DRJCRxJyQouc5qG87zM4QrPCTiiEIuSqkClVHQwNlme7wZt-nQ5p7bHYxHkyS0L2sEW5sKNvCstiJxozN8vV5v95fodvVjP0lJuOSgNsv2STunNQW2jWBc3JENllxdbdLmeZUoV0RctytRyWb1s-7pcZ0mpkW83mVVXodkabGRM0XB01VrryI282WRWdNQg54bYmTLawaZJhpJJQVFxmVYQnkxqaCRLwdEBKTAsq_AyndzDCmdxS4ySRHLXDOKOC21di7ueg3QTxh2ETN2G92RVhb7_CQPfsKtQ4FmaY27rCvQ0zzFlQnWs_XFwOH4tgsWmrofioRszJJaORKKx0Ck7GQfPJ0advvlx9-ODxy8Wnh00vkSOpkJ7E4l-0ctL_WplaTbLBUZFVEVtvWllKt6ilGkxs-2yC9uLXYYSGXWOS1ObYbAZvrIXnrR82SQMn1A8p-9D7ygMHp0L7Z4_4488jYJhdLbvmYMs1bHdnt6roZpRKDDdomcFOu5neu7aatdYC3qZINUsrGxHwfsLoZOLO_-OPvw5_vxr6XDylrGuWJWmIrE5p-R6ksL3B1W7zTVywrxa6BqtzjrnS6tuwHRac9ux0NfRXAr9Bw2&cbcxt=&username=e975263%40iberdrola.com&mkt=&lc=, mas deveria iniciar com https://diretrizes.dev.neoenergia.net/.\n", "trace": "  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"features\\steps\\test_login_steps.py\", line 60, in step_verify_user_logged_in\n    raise AssertionError(f\"O login não foi bem-sucedido; URL atual é {current_url}, mas deveria iniciar com {expected_url}.\")\n"}, "steps": [{"name": "Given que eu acesso a página de login", "status": "passed", "steps": [{"name": "Acessando a página de login", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x0000024CD3BD42C0>"}], "start": 1743784748168, "stop": 1743784748612}], "start": 1743784748167, "stop": 1743784748612}, {"name": "When eu clico no botão Entrar", "status": "passed", "steps": [{"name": "Clicando no botão Entrar", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x0000024CD3BD42C0>"}], "start": 1743784748613, "stop": 1743784755086}], "start": 1743784748612, "stop": 1743784755086}, {"name": "When eu insiro o email de usuario", "status": "passed", "steps": [{"name": "Inserindo o email do usuário", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x0000024CD3BD42C0>"}], "start": 1743784755087, "stop": 1743784756211}], "start": 1743784755086, "stop": 1743784756211}, {"name": "When eu clico no botão Seguinte", "status": "passed", "steps": [{"name": "Clicando no botão Seguinte", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x0000024CD3BD42C0>"}], "start": 1743784756213, "stop": 1743784787331}], "start": 1743784756211, "stop": 1743784787331}, {"name": "When eu preencho o ADFS com usuário e senha", "status": "passed", "steps": [{"name": "Preenchendo o ADFS com usuário e senha", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x0000024CD3BD42C0>"}], "start": 1743784787333, "stop": 1743784795889}], "start": 1743784787331, "stop": 1743784795889}, {"name": "Then eu verifico que o usuário acessou o sistema", "status": "failed", "statusDetails": {"message": "AssertionError: O login não foi bem-sucedido; URL atual é https://ibfs.iberdrola.com/adfs/ls/wia?client-request-id=019601ab-a6da-7e64-adb3-e354baf79aef&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQQIARAAjVJLaxNhFM3XaWMMaKOiCN1kUYpYZzKPzEwmULBpYzpJmtAmaZJBkHl8XzKTeXVmktgIrl1JVyLdqeAiItS6ka7c2lV3ShEUBZEutNSFBTem_6BwuZwD557FOTcaZgiaJ8ibGE2Q6WmBo2Se5lI4jTQGT0JWw1OppIJDTUMax_MIqZR3ORp7BZ6Ag5faw9dvv1d3_279HoKZdhC4fjqR0HQPBp4-gD6hwR5hQwfa0Gvp8ggGiXcA7APwE4Dh2DRJCRxJyQouc5qG87zM4QrPCTiiEIuSqkClVHQwNlme7wZt-nQ5p7bHYxHkyS0L2sEW5sKNvCstiJxozN8vV5v95fodvVjP0lJuOSgNsv2STunNQW2jWBc3JENllxdbdLmeZUoV0RctytRyWb1s-7pcZ0mpkW83mVVXodkabGRM0XB01VrryI282WRWdNQg54bYmTLawaZJhpJJQVFxmVYQnkxqaCRLwdEBKTAsq_AyndzDCmdxS4ySRHLXDOKOC21di7ueg3QTxh2ETN2G92RVhb7_CQPfsKtQ4FmaY27rCvQ0zzFlQnWs_XFwOH4tgsWmrofioRszJJaORKKx0Ck7GQfPJ0advvlx9-ODxy8Wnh00vkSOpkJ7E4l-0ctL_WplaTbLBUZFVEVtvWllKt6ilGkxs-2yC9uLXYYSGXWOS1ObYbAZvrIXnrR82SQMn1A8p-9D7ygMHp0L7Z4_4488jYJhdLbvmYMs1bHdnt6roZpRKDDdomcFOu5neu7aatdYC3qZINUsrGxHwfsLoZOLO_-OPvw5_vxr6XDylrGuWJWmIrE5p-R6ksL3B1W7zTVywrxa6BqtzjrnS6tuwHRac9ux0NfRXAr9Bw2&cbcxt=&username=e975263%40iberdrola.com&mkt=&lc=, mas deveria iniciar com https://diretrizes.dev.neoenergia.net/.\n", "trace": "  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"features\\steps\\test_login_steps.py\", line 60, in step_verify_user_logged_in\n    raise AssertionError(f\"O login não foi bem-sucedido; URL atual é {current_url}, mas deveria iniciar com {expected_url}.\")\n"}, "steps": [{"name": "Verificando que o usuário acessou o sistema", "status": "failed", "statusDetails": {"message": "AssertionError: O login não foi bem-sucedido; URL atual é https://ibfs.iberdrola.com/adfs/ls/wia?client-request-id=019601ab-a6da-7e64-adb3-e354baf79aef&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQQIARAAjVJLaxNhFM3XaWMMaKOiCN1kUYpYZzKPzEwmULBpYzpJmtAmaZJBkHl8XzKTeXVmktgIrl1JVyLdqeAiItS6ka7c2lV3ShEUBZEutNSFBTem_6BwuZwD557FOTcaZgiaJ8ibGE2Q6WmBo2Se5lI4jTQGT0JWw1OppIJDTUMax_MIqZR3ORp7BZ6Ag5faw9dvv1d3_279HoKZdhC4fjqR0HQPBp4-gD6hwR5hQwfa0Gvp8ggGiXcA7APwE4Dh2DRJCRxJyQouc5qG87zM4QrPCTiiEIuSqkClVHQwNlme7wZt-nQ5p7bHYxHkyS0L2sEW5sKNvCstiJxozN8vV5v95fodvVjP0lJuOSgNsv2STunNQW2jWBc3JENllxdbdLmeZUoV0RctytRyWb1s-7pcZ0mpkW83mVVXodkabGRM0XB01VrryI282WRWdNQg54bYmTLawaZJhpJJQVFxmVYQnkxqaCRLwdEBKTAsq_AyndzDCmdxS4ySRHLXDOKOC21di7ueg3QTxh2ETN2G92RVhb7_CQPfsKtQ4FmaY27rCvQ0zzFlQnWs_XFwOH4tgsWmrofioRszJJaORKKx0Ck7GQfPJ0advvlx9-ODxy8Wnh00vkSOpkJ7E4l-0ctL_WplaTbLBUZFVEVtvWllKt6ilGkxs-2yC9uLXYYSGXWOS1ObYbAZvrIXnrR82SQMn1A8p-9D7ygMHp0L7Z4_4488jYJhdLbvmYMs1bHdnt6roZpRKDDdomcFOu5neu7aatdYC3qZINUsrGxHwfsLoZOLO_-OPvw5_vxr6XDylrGuWJWmIrE5p-R6ksL3B1W7zTVywrxa6BqtzjrnS6tuwHRac9ux0NfRXAr9Bw2&cbcxt=&username=e975263%40iberdrola.com&mkt=&lc=, mas deveria iniciar com https://diretrizes.dev.neoenergia.net/.\n", "trace": "  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"features\\steps\\test_login_steps.py\", line 60, in step_verify_user_logged_in\n    raise AssertionError(f\"O login não foi bem-sucedido; URL atual é {current_url}, mas deveria iniciar com {expected_url}.\")\n"}, "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x0000024CD3BD42C0>"}], "start": 1743784795890, "stop": 1743784795912}], "start": 1743784795889, "stop": 1743784795916}], "start": 1743784748165, "stop": 1743784795916, "uuid": "f0ee37c6-de1b-4aa8-9bd2-2fcd71add7e2", "historyId": "ae432aaa735ff3101a8e6fa41e11feb9", "fullName": "Acessar a página de login e testar fluxo de tela de usuários: Acessar a página de login com sucesso", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Acessar a página de login e testar fluxo de tela de usuários"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}